### ISSUE TITLE
C1-2818-9 (PSM Runtime)

### ISSUE THREAD

**Issue by ghost** [SKGleba/PKGinstallerLauncher#4]
I installed PKGInstallerLauncher and I downloaded the 3 pkg files of PSM runtime. When I ran the installation of the first one, I received this error:
*failed..
(C1-2818-9)*

I tried on PKGJ too and I got an error.
[Issue on PKGJ](https://github.com/blastrock/pkgj/issues/369)

Hardware: PSV
Version: 3.60 Enso
Running under SD2VITA.

**Comment by andrew-stclair** [comment]
I also have this issue, any help would be much appreciated

**Comment by andrew-stclair** [comment]
Ok, turns out i had reF00D installed but was not getting the black screen.

disabling it temporarily to install the packages worked for me

**Comment by 0oNT21o0** [comment]
Thank you! It worked.

**Comment by ghost** [comment]
Thank you! It worked.
